import { act, renderHook, waitFor } from "@testing-library/react";
import { beforeEach, expect, it, vi } from "vitest";
vi.mock("@thechat/client/platform/environment", () => ({ isWeb: true }));
vi.mock("@thechat/client/lib/api", () => ({ api: { auth: { me: { get: vi.fn() }, logout: { post: vi.fn() }, login: { post: vi.fn() } } } }));
import { usePlatformLifecycle } from "./shell.web";
import { useAuthStore } from "@thechat/client/stores/auth";
import { api } from "@thechat/client/lib/api";
import { queryClient } from "@thechat/client/lib/query-client";
const alice = { id: "alice", name: "Alice", email: "a@example.invalid", type: "human", avatar: null } as const;
beforeEach(() => { vi.clearAllMocks(); localStorage.clear(); useAuthStore.setState({ user: null, token: null, loading: true }); });
it("invalidates another tab's private state immediately then revalidates identity with the server", async () => {
  vi.mocked(api.auth.me.get).mockResolvedValue({ data: { user: alice }, error: null } as never);
  const mounted = renderHook(() => usePlatformLifecycle(null));
  await waitFor(() => expect(useAuthStore.getState().user?.id).toBe("alice"));
  queryClient.setQueryData(["private"], "alice-secret");
  let finish!: (value: unknown) => void;
  vi.mocked(api.auth.me.get).mockImplementation(() => new Promise(resolve => { finish = resolve as never; }) as never);
  act(() => window.dispatchEvent(new StorageEvent("storage", { key: "thechat:session-changed", newValue: "credential-free-signal" })));
  expect(useAuthStore.getState().user).toBeNull();
  expect(queryClient.getQueryData(["private"])).toBeUndefined();
  await waitFor(() => expect(finish).toBeDefined());
  await act(async () => { finish({ data: { user: { ...alice, id: "bob" } }, error: null }); });
  await waitFor(() => expect(useAuthStore.getState().user?.id).toBe("bob"));
  expect(useAuthStore.getState().token).toBeNull();
  mounted.unmount();
});
it("announces successful auth changes without placing a credential or identity in storage", async () => {
  vi.mocked(api.auth.login.post).mockResolvedValue({ data: { user: alice }, error: null } as never);
  await useAuthStore.getState().login(alice.email, "secret-password");
  expect(localStorage.getItem("thechat:session-changed")).toBeTruthy();
  const serialized = JSON.stringify({ ...localStorage });
  expect(serialized).not.toContain("alice"); expect(serialized).not.toContain("secret");
});
