import { act, cleanup, fireEvent, render, screen, waitFor, within } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { DirectHermesTestSocket } from "../lib/direct-hermes-test-transport";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { StrictMode } from "react";
import { clearDirectHermesChats } from "../hooks/useDirectHermesChat";

const { proxyTicketPost, nativePick, nativeInvoke } = vi.hoisted(() => ({ proxyTicketPost: vi.fn(), nativePick: vi.fn(), nativeInvoke: vi.fn() }));
vi.mock("@tauri-apps/plugin-dialog", () => ({ open: nativePick }));
vi.mock("@tauri-apps/api/core", () => ({ invoke: nativeInvoke }));
vi.mock("../lib/api", () => ({ api: { bots: () => ({ "hermes-rpc": { "proxy-ticket": { post: proxyTicketPost } } }) } }));
import { DirectHermesSessionsView } from "./DirectHermesSessionsView";

let socket: DirectHermesTestSocket;
let sequence = 0;
function renderView() {
  return render(<QueryClientProvider client={new QueryClient({ defaultOptions: { queries: { retry: false } } })}><DirectHermesSessionsView botId={`bot-${++sequence}`} botName="Hermes" conversationId="conversation-1" token="thechat-user-token" /></QueryClientProvider>);
}
beforeEach(() => {
  proxyTicketPost.mockResolvedValue({ data: { ticket: "A".repeat(43), expiresAt: new Date(Date.now() + 30_000), proxyUrl: "wss://test.invalid/hermes-proxy" }, error: null });
  const Native = WebSocket;
  vi.stubGlobal("WebSocket", class extends DirectHermesTestSocket {
    static OPEN = Native.OPEN; static CONNECTING = Native.CONNECTING; static CLOSED = Native.CLOSED;
    constructor() {
      super(); socket = this;
      const original = this.handle;
      this.handle = (method, params) => method === "commands.catalog" ? { pairs: [["/branch", "Branch the current session"], ["/model", "Inspect the current model"]] } : original(method, params);
      queueMicrotask(() => this.open());
    }
  });
});
afterEach(() => { cleanup(); clearDirectHermesChats(); vi.unstubAllGlobals(); vi.clearAllMocks(); });

describe("Direct Hermes desktop surface", () => {
  it("renders attachment upload errors and permits local removal without another RPC", async () => {
    renderView(); await screen.findByText("Connected");
    fireEvent.click(screen.getByRole("button", { name: "New session" }));
    await waitFor(() => expect(screen.getByRole("textbox", { name: "Message Hermes" })).toBeEnabled());
    const original = socket.handle;
    socket.handle = (method, params) => { if (method === "file.attach") throw new Error("Upload rejected by Hermes"); return original(method, params); };
    fireEvent.change(screen.getByLabelText("Choose attachments"), { target: { files: [new File(["x"], "failed.txt")] } });
    fireEvent.click(screen.getByRole("button", { name: "Send" }));
    const pending = await screen.findByRole("list", { name: "Pending attachments" });
    expect(await within(pending).findByRole("alert")).toHaveTextContent("Upload rejected by Hermes");
    const before = socket.calls.length;
    fireEvent.click(screen.getByRole("button", { name: "Remove failed.txt" }));
    await waitFor(() => expect(screen.queryByRole("list", { name: "Pending attachments" })).not.toBeInTheDocument());
    expect(socket.calls).toHaveLength(before);
    expect(socket.calls.some(call => call.method === "prompt.submit")).toBe(false);
  });
  it("keeps native picker/read completions out of a different session and preserves queued files on return", async () => {
    vi.stubGlobal("__TAURI_INTERNALS__", {});
    let finish!: (value: ArrayBufferLike) => void;
    nativePick.mockResolvedValue(["C:\\private\\late.txt"]);
    nativeInvoke.mockImplementation(() => new Promise(resolve => { finish = resolve; }));
    renderView(); await screen.findByText("Connected");
    fireEvent.click(screen.getByRole("button", { name: "New session" }));
    await waitFor(() => expect(screen.getByRole("textbox", { name: "Message Hermes" })).toBeEnabled());
    fireEvent.change(screen.getByLabelText("Choose attachments"), { target: { files: [new File(["draft"], "original.txt")] } });
    fireEvent.click(screen.getByRole("button", { name: "Attach files" }));
    await waitFor(() => expect(finish).toBeTypeOf("function"));
    expect(screen.getByText("Choosing / reading files…")).toBeInTheDocument();
    expect(screen.getByRole("button", { name: "Send" })).toBeDisabled();
    fireEvent.click(screen.getByRole("button", { name: "Saved A" }));
    await waitFor(() => expect(screen.getByRole("textbox", { name: "Message Hermes" })).toBeEnabled());
    await act(async () => finish(new TextEncoder().encode("late").buffer));
    expect(screen.queryByText("late.txt")).not.toBeInTheDocument();
    expect(screen.queryByText("original.txt")).not.toBeInTheDocument();
    fireEvent.click(screen.getByRole("button", { name: /New sessionReady/ }));
    expect(screen.getByRole("button", { name: "Remove original.txt" })).toBeEnabled();
    expect(screen.queryByText("late.txt")).not.toBeInTheDocument();
    expect(socket.calls.some(call => call.method === "file.attach")).toBe(false);
  });
  it("abandons a late native dialog when the bot/controller changes even if the active key is reused", async () => {
    vi.stubGlobal("__TAURI_INTERNALS__", {});
    let choose!: (value: string[]) => void;
    nativePick.mockImplementation(() => new Promise(resolve => { choose = resolve; }));
    const props = { botId: `bot-${++sequence}`, botName: "Hermes", conversationId: "conversation-1", token: "thechat-user-token" };
    const view = render(<DirectHermesSessionsView {...props} />);
    await screen.findByText("Connected");
    fireEvent.click(screen.getByRole("button", { name: "New session" }));
    await waitFor(() => expect(screen.getByRole("textbox", { name: "Message Hermes" })).toBeEnabled());
    fireEvent.click(screen.getByRole("button", { name: "Attach files" }));
    await waitFor(() => expect(choose).toBeTypeOf("function"));
    view.rerender(<DirectHermesSessionsView {...props} botId={`bot-${++sequence}`} />);
    await screen.findByText("Connected");
    fireEvent.click(screen.getByRole("button", { name: "New session" }));
    await waitFor(() => expect(screen.getByRole("textbox", { name: "Message Hermes" })).toBeEnabled());
    await act(async () => choose(["C:\\private\\wrong-bot.txt"]));
    expect(nativeInvoke).not.toHaveBeenCalled();
    expect(screen.queryByText("wrong-bot.txt")).not.toBeInTheDocument();
    expect(screen.getByRole("button", { name: "Attach files" })).toBeEnabled();
  });
  it("reports native read failures without exposing local paths and lets the user choose again", async () => {
    vi.stubGlobal("__TAURI_INTERNALS__", {});
    nativePick.mockResolvedValue(["C:\\private\\secret.txt"]);
    nativeInvoke.mockRejectedValue(new Error("Cannot read C:\\private\\secret.txt"));
    renderView(); await screen.findByText("Connected");
    fireEvent.click(screen.getByRole("button", { name: "New session" }));
    await waitFor(() => expect(screen.getByRole("textbox", { name: "Message Hermes" })).toBeEnabled());
    fireEvent.click(screen.getByRole("button", { name: "Attach files" }));
    const alert = await screen.findByRole("alert");
    expect(alert).toHaveTextContent("Could not read the selected files.");
    expect(alert).not.toHaveTextContent("C:\\private");
    expect(screen.getByRole("button", { name: "Attach files" })).toBeEnabled();
    expect(socket.calls.some(call => call.method === "file.attach")).toBe(false);
  });
  it("shows file count and byte limit errors without queuing or uploading rejected files", async () => {
    renderView(); await screen.findByText("Connected");
    fireEvent.click(screen.getByRole("button", { name: "New session" }));
    await waitFor(() => expect(screen.getByRole("textbox", { name: "Message Hermes" })).toBeEnabled());
    const picker = screen.getByLabelText("Choose attachments");
    fireEvent.change(picker, { target: { files: [new File([new Uint8Array(2 * 1024 * 1024 + 1)], "too-large.bin")] } });
    expect(await screen.findByRole("alert")).toHaveTextContent("2 MiB");
    expect(screen.queryByRole("list", { name: "Pending attachments" })).not.toBeInTheDocument();
    fireEvent.change(picker, { target: { files: Array.from({ length: 6 }, (_, index) => new File(["x"], `${index}.txt`)) } });
    expect(await screen.findByRole("alert")).toHaveTextContent("5");
    expect(screen.queryByRole("list", { name: "Pending attachments" })).not.toBeInTheDocument();
    expect(screen.getByRole("button", { name: "Send" })).toBeDisabled();
    expect(socket.calls.some(call => call.method === "file.attach")).toBe(false);
  });
  it("uses the same send guard for Enter and Send while preserving IME and Shift+Enter", async () => {
    renderView(); await screen.findByText("Connected");
    let create!: (value: unknown) => void;
    const original = socket.handle;
    socket.handle = (method, params) => method === "session.resume" ? new Promise(resolve => { create = resolve; }) : original(method, params);
    fireEvent.click(screen.getByRole("button", { name: "Saved A" }));
    const input = await screen.findByRole("textbox", { name: "Message Hermes" });
    expect(input).toBeDisabled();
    expect(screen.getByRole("button", { name: "Attach files" })).toBeDisabled();
    expect(screen.getByRole("button", { name: "Send" })).toBeDisabled();
    fireEvent.keyDown(input, { key: "Enter" });
    await waitFor(() => expect(create).toBeTypeOf("function"));
    await act(async () => create({ session_id: "runtime-1", stored_session_id: "stored-1", messages: [] }));
    fireEvent.change(input, { target: { value: "Hello" } });
    expect(fireEvent.keyDown(input, { key: "Enter", shiftKey: true })).toBe(true);
    expect(fireEvent.keyDown(input, { key: "Enter", isComposing: true })).toBe(true);
    expect(fireEvent.keyDown(input, { key: "Enter", keyCode: 229 })).toBe(true);
    expect(socket.calls.filter(call => call.method === "prompt.submit")).toHaveLength(0);
    fireEvent.keyDown(input, { key: "Enter" });
    await waitFor(() => expect(input).toHaveValue(""));
    fireEvent.change(input, { target: { value: "Next" } });
    expect(screen.getByRole("button", { name: "Send" })).toBeDisabled();
    fireEvent.keyDown(input, { key: "Enter" });
    act(() => socket.close());
    expect(input).toBeDisabled();
    expect(screen.getByRole("button", { name: "Attach files" })).toBeDisabled();
    fireEvent.keyDown(input, { key: "Enter" });
    fireEvent.submit(screen.getByRole("form", { name: "Hermes composer" }));
    expect(socket.calls.filter(call => call.method === "prompt.submit")).toHaveLength(1);
    expect(input).toHaveValue("Next");
  });
  it("does not pass unknown slash commands off as ordinary chat", async () => {
    renderView(); await screen.findByText("Connected");
    fireEvent.click(screen.getByRole("button", { name: "New session" }));
    await waitFor(() => expect(screen.getByRole("textbox", { name: "Message Hermes" })).toBeEnabled());
    const input = screen.getByRole("textbox", { name: "Message Hermes" });
    fireEvent.change(input, { target: { value: "/not-a-hermes-command" } });
    expect(screen.getByText(/Send to run a Hermes command, not a chat message/)).toBeInTheDocument();
    fireEvent.click(screen.getByRole("button", { name: "Send" }));
    expect(await screen.findByRole("alert")).toHaveTextContent("not supported");
    expect(input).toHaveValue("/not-a-hermes-command");
    expect(socket.calls.some(call => call.method === "prompt.submit")).toBe(false);
  });
  it("shows gateway slash metadata, selects without dispatch and branches through RPC while retaining the parent", async () => {
    renderView(); await screen.findByText("Connected");
    fireEvent.click(screen.getByRole("button", { name: "New session" }));
    await waitFor(() => expect(screen.getByRole("textbox", { name: "Message Hermes" })).toBeEnabled());
    const input = screen.getByRole("textbox", { name: "Message Hermes" });
    fireEvent.change(input, { target: { value: "/br" } });
    const palette = await screen.findByRole("list", { name: "Hermes commands" });
    const before = socket.calls.length;
    fireEvent.click(within(palette).getByRole("button", { name: "/branch — Branch the current session" }));
    expect(input).toHaveValue("/branch ");
    expect(input).toHaveFocus();
    expect(socket.calls).toHaveLength(before);
    const original = socket.handle;
    socket.handle = (method, params) => method === "session.branch" ? { session_id: "runtime-child", stored_session_id: "stored-child", title: "Branched session", messages: [] } : original(method, params);
    fireEvent.change(input, { target: { value: "/branch Branched session" } });
    fireEvent.keyDown(input, { key: "Enter" });
    await waitFor(() => expect(screen.getByRole("button", { name: /Branched sessionReady/ })).toHaveAttribute("aria-pressed", "true"));
    expect(socket.calls.filter(call => call.method === "session.branch")).toEqual([expect.objectContaining({ params: { session_id: "runtime-1", name: "Branched session" } })]);
    expect(socket.calls.filter(call => call.method === "prompt.submit")).toHaveLength(0);
    fireEvent.click(screen.getByRole("button", { name: /New sessionReady/ }));
    expect(screen.getByRole("textbox", { name: "Message Hermes" })).toHaveValue("");
    expect(screen.getByText("stored-1")).toBeInTheDocument();
  });
  it("previews bounded local images and releases object URLs on removal and unmount", async () => {
    const create = vi.fn(() => "blob:local-preview");
    const revoke = vi.fn();
    vi.stubGlobal("URL", class extends URL { static createObjectURL = create; static revokeObjectURL = revoke; });
    const view = renderView(); await screen.findByText("Connected");
    fireEvent.click(screen.getByRole("button", { name: "New session" }));
    await waitFor(() => expect(screen.getByRole("textbox", { name: "Message Hermes" })).toBeEnabled());
    const png = Uint8Array.from(atob("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jE1sAAAAASUVORK5CYII="), char => char.charCodeAt(0));
    const file = new File([png], "tiny.png", { type: "image/png" });
    fireEvent.change(screen.getByLabelText("Choose attachments"), { target: { files: [file] } });
    expect(await screen.findByRole("img", { name: "Local preview of tiny.png" })).toHaveAttribute("src", "blob:local-preview");
    expect(create).toHaveBeenCalledWith(file);
    fireEvent.click(screen.getByRole("button", { name: "Remove tiny.png" }));
    await waitFor(() => expect(revoke).toHaveBeenCalledTimes(1));
    fireEvent.change(screen.getByLabelText("Choose attachments"), { target: { files: [file] } });
    await screen.findByRole("img", { name: "Local preview of tiny.png" });
    view.unmount();
    expect(revoke).toHaveBeenCalledTimes(2);
  });
  it("sends an attachment-only message once, displays upload progress and retains honest transcript metadata", async () => {
    renderView(); await screen.findByText("Connected");
    fireEvent.click(screen.getByRole("button", { name: "New session" }));
    await waitFor(() => expect(screen.getByRole("textbox", { name: "Message Hermes" })).toBeEnabled());
    const original = socket.handle;
    let upload!: (value: unknown) => void;
    socket.handle = (method, params) => method === "file.attach" ? new Promise(resolve => { upload = resolve; }) : original(method, params);
    fireEvent.change(screen.getByLabelText("Choose attachments"), { target: { files: [new File(["notes"], "notes.txt", { type: "text/plain" })] } });
    await screen.findByRole("button", { name: "Remove notes.txt" });
    fireEvent.keyDown(screen.getByRole("textbox", { name: "Message Hermes" }), { key: "Enter" });
    await waitFor(() => expect(upload).toBeTypeOf("function"));
    expect(screen.getByText("Uploading…")).toBeInTheDocument();
    expect(screen.getByRole("button", { name: "Send" })).toBeDisabled();
    expect(screen.getByRole("button", { name: "Attach files" })).toBeDisabled();
    expect(screen.getByRole("button", { name: "Remove notes.txt" })).toBeDisabled();
    fireEvent.submit(screen.getByRole("form", { name: "Hermes composer" }));
    fireEvent.keyDown(screen.getByRole("textbox", { name: "Message Hermes" }), { key: "Enter" });
    await act(async () => upload({ attached: true, path: "/hermes/uploads/notes.txt", ref_text: "[Attached file: /hermes/uploads/notes.txt]" }));
    await waitFor(() => expect(screen.queryByRole("list", { name: "Pending attachments" })).not.toBeInTheDocument());
    expect(screen.getByText("notes.txt")).toBeInTheDocument();
    expect(screen.queryByRole("img")).not.toBeInTheDocument();
    const uploads = socket.calls.filter(call => call.method === "file.attach");
    expect(uploads).toHaveLength(1);
    expect(uploads[0].params).toMatchObject({ session_id: "runtime-1", name: "notes.txt", data_url: "data:text/plain;base64,bm90ZXM=" });
    expect(socket.calls.filter(call => call.method === "prompt.submit")).toHaveLength(1);
  });
  it("handles image paste and file drop only inside this composer without consuming text paste", async () => {
    renderView(); await screen.findByText("Connected");
    fireEvent.click(screen.getByRole("button", { name: "New session" }));
    await waitFor(() => expect(screen.getByRole("textbox", { name: "Message Hermes" })).toBeEnabled());
    const input = screen.getByRole("textbox", { name: "Message Hermes" });
    const image = new File(["png"], "pasted.png", { type: "image/png" });
    const clipboardData = { items: [{ kind: "file", type: "image/png", getAsFile: () => image }], getData: () => "" };
    expect(fireEvent.paste(document.body, { clipboardData })).toBe(true);
    expect(screen.queryByRole("button", { name: "Remove pasted.png" })).not.toBeInTheDocument();
    expect(fireEvent.paste(input, { clipboardData: { items: [{ kind: "string", type: "text/plain" }], getData: () => "ordinary pasted text" } })).toBe(true);
    expect(fireEvent.paste(input, { clipboardData })).toBe(false);
    await screen.findByRole("button", { name: "Remove pasted.png" });
    const composer = screen.getByRole("form", { name: "Hermes composer" });
    const drop = { dataTransfer: { types: ["Files"], files: [new File(["drop"], "dropped.txt", { type: "text/plain" })] } };
    expect(fireEvent.drop(document.body, drop)).toBe(true);
    expect(screen.queryByRole("button", { name: "Remove dropped.txt" })).not.toBeInTheDocument();
    expect(fireEvent.drop(composer, drop)).toBe(false);
    await screen.findByRole("button", { name: "Remove dropped.txt" });
    expect(fireEvent.drop(composer, { dataTransfer: { types: ["text/plain"], files: [] } })).toBe(true);
    expect(socket.calls.some(call => call.method === "file.attach")).toBe(false);
  });
  it("uses the Windows/Tauri picker and reads selected bytes without uploading local paths", async () => {
    vi.stubGlobal("__TAURI_INTERNALS__", {});
    nativePick.mockResolvedValue(["C:\\Users\\Bruno\\notes.txt"]);
    nativeInvoke.mockResolvedValue(new TextEncoder().encode("notes").buffer);
    renderView(); await screen.findByText("Connected");
    fireEvent.click(screen.getByRole("button", { name: "New session" }));
    await waitFor(() => expect(screen.getByRole("textbox", { name: "Message Hermes" })).toBeEnabled());
    const before = socket.calls.length;
    fireEvent.click(screen.getByRole("button", { name: "Attach files" }));
    await waitFor(() => expect(nativePick).toHaveBeenCalledWith({ multiple: true, directory: false, title: "Attach files to Hermes" }));
    await screen.findByRole("button", { name: "Remove notes.txt" });
    expect(nativeInvoke).toHaveBeenCalledWith("read_dropped_file", { filePath: "C:\\Users\\Bruno\\notes.txt" });
    expect(screen.getByText("5 bytes")).toBeInTheDocument();
    expect(socket.calls).toHaveLength(before);
    expect(JSON.stringify(socket.calls)).not.toContain("C:\\Users");
  });
  it("queues multiple picker files locally and removes them without network activity", async () => {
    renderView(); await screen.findByText("Connected");
    fireEvent.click(screen.getByRole("button", { name: "New session" }));
    await waitFor(() => expect(screen.getByRole("textbox", { name: "Message Hermes" })).toBeEnabled());
    const attach = screen.getByRole("button", { name: "Attach files" });
    const picker = screen.getByLabelText("Choose attachments");
    expect(picker).toHaveAttribute("type", "file");
    expect(picker).toHaveAttribute("multiple");
    const click = vi.spyOn(picker as HTMLInputElement, "click");
    fireEvent.click(attach);
    expect(click).toHaveBeenCalledOnce();
    const before = socket.calls.length;
    fireEvent.change(picker, { target: { files: [new File(["notes"], "notes.txt", { type: "text/plain" }), new File(["data"], "data.csv", { type: "text/csv" })] } });
    await screen.findByRole("button", { name: "Remove notes.txt" });
    expect(screen.getByRole("button", { name: "Remove data.csv" })).toBeEnabled();
    expect(screen.getAllByText("Queued · uploads on Send")).toHaveLength(2);
    expect(screen.getByText(/Up to 5 files · 2 MiB each/)).toBeInTheDocument();
    expect(screen.getByRole("button", { name: "Send" })).toBeEnabled();
    fireEvent.click(screen.getByRole("button", { name: "Remove notes.txt" }));
    await waitFor(() => expect(screen.queryByRole("button", { name: "Remove notes.txt" })).not.toBeInTheDocument());
    fireEvent.click(screen.getByRole("button", { name: "Remove data.csv" }));
    await waitFor(() => expect(screen.getByRole("button", { name: "Send" })).toBeDisabled());
    expect(socket.calls).toHaveLength(before);
  });
  it("explains the shared gateway boundary to every chat participant", async () => {
    renderView();
    await screen.findByText("Connected");
    expect(screen.getByText("Sessions are shared with anyone granted access to this Hermes gateway.")).toBeInTheDocument();
    expect(screen.queryByText(/Private connection/)).not.toBeInTheDocument();
  });
  it("refreshes in place without inserting a loading row or resetting the session list", async () => {
    renderView();
    const row = await screen.findByRole("button", { name: "Saved A" });
    const list = row.parentElement!;
    const children = Array.from(list.children);
    list.scrollTop = 37;
    let complete!: (value: unknown) => void;
    const original = socket.handle;
    socket.handle = (method, params) => method === "session.list"
      ? new Promise(resolve => { complete = resolve; }) : original(method, params);
    fireEvent.click(screen.getByRole("button", { name: "Refresh" }));
    expect(screen.queryByText("Loading sessions…")).not.toBeInTheDocument();
    expect(screen.getByRole("button", { name: "Refreshing sessions" })).toBeDisabled();
    expect(screen.getByRole("button", { name: "Refreshing sessions" })).toHaveAttribute("aria-busy", "true");
    expect(Array.from(list.children)).toEqual(children);
    expect(screen.getByRole("button", { name: "Saved A" })).toBe(row);
    expect(list.scrollTop).toBe(37);
    await waitFor(() => expect(complete).toBeTypeOf("function"));
    await act(async () => complete({ sessions: [{ id: "saved-a", title: "Saved A" }, { id: "saved-b", title: "Saved B" }] }));
    expect(screen.getByRole("button", { name: "Refresh" })).toBeEnabled();
    expect(screen.getByRole("button", { name: "Saved A" })).toBe(row);
    expect(list.scrollTop).toBe(37);
  });
  it("connects once under StrictMode effect replay using the real client and transport", async () => {
    render(<StrictMode><DirectHermesSessionsView botId={`strict-${++sequence}`} botName="Hermes" conversationId="conversation-1" token="thechat-user-token" /></StrictMode>);
    await screen.findByText("Connected");
    expect(proxyTicketPost).toHaveBeenCalledTimes(1);
    expect(socket.readyState).toBe(WebSocket.OPEN);
    fireEvent.click(screen.getByRole("button", { name: "New session" }));
    const input = await screen.findByRole("textbox", { name: "Message Hermes" });
    fireEvent.change(input, { target: { value: "Strict mode prompt" } }); fireEvent.click(screen.getByRole("button", { name: "Send" }));
    await waitFor(() => expect(input).toHaveValue(""));
    expect(socket.calls.filter(call => call.method === "prompt.submit")).toHaveLength(1);
  });
  it("offers explicit approval and clarification controls and truthful unsupported-interaction guidance", async () => {
    renderView(); await screen.findByText("Connected");
    fireEvent.click(screen.getByRole("button", { name: "New session" }));
    await screen.findByRole("textbox", { name: "Message Hermes" });
    socket.handle = method => method === "approval.respond" ? { resolved: 1 } : { status: "ok" };
    act(() => socket.event("approval.request", { request_id: "a1", command: "rm example", description: "Confirm deletion" }));
    expect(screen.getByText("rm example")).toBeInTheDocument();
    fireEvent.click(screen.getByRole("button", { name: "Allow once" }));
    await waitFor(() => expect(screen.queryByRole("button", { name: "Allow once" })).not.toBeInTheDocument());
    act(() => socket.event("clarify.request", { request_id: "q1", question: "Which folder?", choices: ["src", "test"] }));
    fireEvent.change(screen.getByRole("textbox", { name: "Answer" }), { target: { value: "src" } });
    fireEvent.click(screen.getByRole("button", { name: "Submit answer" }));
    await waitFor(() => expect(socket.calls.at(-1)).toMatchObject({ method: "clarify.respond", params: { request_id: "q1", answer: "src" } }));
    act(() => socket.event("secret.request", { request_id: "s1", name: "API key" }));
    expect(screen.getByText(/This interaction requires the Hermes app/)).toBeInTheDocument();
    expect(screen.getByRole("button", { name: "Stop" })).toBeEnabled();
  });
  it("keeps a running session and draft alive across navigation away and back", async () => {
    const props = { botId: `bot-${++sequence}`, botName: "Hermes", conversationId: "conversation-1", token: "thechat-user-token" };
    const view = render(<DirectHermesSessionsView {...props} />);
    await screen.findByText("Connected");
    fireEvent.click(screen.getByRole("button", { name: "New session" }));
    const input = await screen.findByRole("textbox", { name: "Message Hermes" });
    fireEvent.change(input, { target: { value: "Run" } }); fireEvent.click(screen.getByRole("button", { name: "Send" }));
    await waitFor(() => expect(input).toHaveValue(""));
    fireEvent.change(input, { target: { value: "My next draft" } });
    const liveSocket = socket;
    view.unmount();
    expect(liveSocket.readyState).toBe(WebSocket.OPEN);
    act(() => liveSocket.event("message.complete", { text: "Finished while away" }));
    render(<DirectHermesSessionsView {...props} />);
    expect(await screen.findByText("Finished while away")).toBeInTheDocument();
    expect(screen.getByRole("textbox", { name: "Message Hermes" })).toHaveValue("My next draft");
    expect(socket).toBe(liveSocket);
    expect(liveSocket.calls.filter(call => call.method === "prompt.submit")).toHaveLength(1);
  });
  it("shows a Sessions sidebar, sends on the direct tunnel, renders live tools and a final Markdown answer", async () => {
    renderView();
    const sidebar = await screen.findByRole("complementary", { name: "Sessions" });
    expect(within(sidebar).getByRole("button", { name: /Saved A/ })).toBeInTheDocument();
    expect(within(sidebar).getByRole("button", { name: /Saved A/ })).toHaveAttribute("aria-pressed", "false");
    expect(within(sidebar).getByRole("button", { name: /Saved B/ })).toHaveAttribute("aria-pressed", "false");
    expect(proxyTicketPost).toHaveBeenCalledWith({ conversationId: "conversation-1" }, { fetch: { signal: expect.any(AbortSignal) }, headers: { authorization: "Bearer thechat-user-token" } });
    fireEvent.click(screen.getByRole("button", { name: "New session" }));
    const composer = await screen.findByRole("textbox", { name: "Message Hermes" });
    await waitFor(() => expect(composer).not.toBeDisabled());
    fireEvent.change(composer, { target: { value: "Inspect the project" } });
    fireEvent.click(screen.getByRole("button", { name: "Send" }));
    await waitFor(() => expect(composer).toHaveValue(""));
    expect(screen.getByRole("button", { name: "Stop" })).toBeEnabled();
    act(() => socket.event("tool.start", { tool_id: "t1", name: "terminal", context: "pwd", args: { command: "pwd" } }));
    expect(screen.getByText("terminal")).toBeInTheDocument();
    act(() => socket.event("tool.complete", { tool_id: "t1", name: "terminal", result: { output: "/project" } }));
    expect(screen.getByText(/\/project/)).toBeInTheDocument();
    act(() => socket.event("message.complete", { text: "The project is **ready**." }));
    expect(screen.getByText("ready").tagName).toBe("STRONG");
    expect(screen.queryByRole("button", { name: "Stop" })).not.toBeInTheDocument();
  });
});
