{{- $apiServiceAccount := .Values.serviceAccount | default dict -}}
{{- $defaultWorkerServiceAccount := dict "create" true "name" "" "annotations" (dict) -}}
{{- $workerServiceAccount := mergeOverwrite (deepCopy $defaultWorkerServiceAccount) (.Values.worker.serviceAccount | default dict) -}}
{{- $clamav := .Values.worker.clamav | default dict -}}
{{- $defaultClamavServiceAccount := dict "create" true "name" "" -}}
{{- $clamavServiceAccount := mergeOverwrite (deepCopy $defaultClamavServiceAccount) (get $clamav "serviceAccount" | default dict) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "thechat-api.serviceAccountName" . }}
  labels:
    {{- include "thechat-api.labels" . | nindent 4 }}
  {{- with (get $apiServiceAccount "annotations") }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if and .Values.worker.enabled (get $workerServiceAccount "create") }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "thechat-api.workerServiceAccountName" . }}
  labels:
    {{- include "thechat-api.workerLabels" . | nindent 4 }}
  {{- with (get $workerServiceAccount "annotations") }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- if and .Values.worker.enabled (get $clamav "enabled") (get $clamavServiceAccount "create") }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "thechat-api.clamavServiceAccountName" . }}
  labels:
    {{- include "thechat-api.clamavLabels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
