import { test, expect, type Page } from '@playwright/test';
import { randomUUID } from 'node:crypto';
import { apiURL, webHeaders, call, identity, login, seedWorkspace, assertContained } from './fixtures';
async function search(page: Page, query: string) {
  await page.keyboard.press('Control+k');
  const dialog = page.getByRole('dialog', { name: 'Search and navigate' });
  await expect(dialog).toBeVisible();
  await dialog.getByRole('combobox', { name: 'Search', exact: true }).fill(query);
  return dialog;
}
test('jump to a bot, task and channel across workspaces with keyboard and touch', async ({ page, request }) => {
  const s = await seedWorkspace(request);
  const ws = await call(request, 'POST', '/workspaces/create', { name: `Search second ${randomUUID().slice(0, 8)}` }, s.a.accessToken);
  const bot = await call(request, 'POST', '/bots/create', { name: 'Koda Search', kind: 'hermes', workspaceId: ws.id }, s.a.accessToken);
  const dm = await call(request, 'POST', '/conversations/dm', { workspaceId: ws.id, otherUserId: bot.userId }, s.a.accessToken);
  const task = await call(request, 'POST', `/conversations/threads/${dm.id}`, { title: 'Search release decisions' }, s.a.accessToken);
  await login(page, s.alice);
  let dialog = await search(page, 'Koda Search');
  await expect(dialog.getByRole('option').first()).toContainText('Koda Search');
  await expect(dialog.getByRole('option').first()).toContainText(ws.name);
  await assertContained(page, '[data-testid=palette-panel]');
  await page.screenshot({ path: `${test.info().outputDir}/jump-palette.png` });
  await page.keyboard.press('Enter');
  await expect(page).toHaveURL(new RegExp(`/dm/${dm.id}`));
  await expect(page.locator('[contenteditable=true]').first()).toBeFocused();
  dialog = await search(page, 'Search release decisions');
  await expect(dialog.getByRole('option').first()).toContainText('Search release decisions');
  await page.keyboard.press('Enter');
  await expect(page).toHaveURL(new RegExp(`threadId=${task.id}`));
  dialog = await search(page, '@Koda Search');
  await expect(dialog.getByRole('button', { name: 'DMs', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await expect(dialog.getByRole('option').first()).toContainText('Koda Search');
  await page.keyboard.press('Enter');
  await expect(page).not.toHaveURL(/threadId=/);
  await page.getByRole('button', { name: 'Search', exact: true }).click();
  dialog = page.getByRole('dialog', { name: 'Search and navigate' });
  await dialog.getByRole('combobox', { name: 'Search', exact: true }).fill('#general');
  await dialog.getByRole('option').filter({ hasText: s.workspace.name }).click();
  await expect(page).toHaveURL(new RegExp(`/channel/${s.channel.id}`));
  await expect(page.locator('[contenteditable=true]').first()).toBeFocused();
  await page.keyboard.press('Control+Shift+p');
  dialog = page.getByRole('dialog', { name: 'Search and navigate' });
  await expect(dialog.getByRole('combobox', { name: 'Search', exact: true })).toHaveValue('>');
  await dialog.getByRole('combobox', { name: 'Search', exact: true }).fill('>Settings');
  await expect(dialog.getByRole('option', { name: /Settings/ })).toHaveCount(1);
  await page.keyboard.press('Escape');
});
test('message results paginate and deep-link to an old task message', async ({ page, request }) => {
  test.setTimeout(120_000);
  const s = await seedWorkspace(request);
  const bot = await call(request, 'POST', '/bots/create', { name: 'Koda History', kind: 'hermes', workspaceId: s.workspace.id }, s.a.accessToken);
  const dm = await call(request, 'POST', '/conversations/dm', { workspaceId: s.workspace.id, otherUserId: bot.userId }, s.a.accessToken);
  const task = await call(request, 'POST', `/conversations/threads/${dm.id}`, { title: 'Historical decisions' }, s.a.accessToken);
  const needle = `archiveneedle${randomUUID().replaceAll('-', '')}`;
  const selected = await call(request, 'POST', `/messages/${dm.id}`, { content: `${needle} old task decision`, threadId: task.id }, s.a.accessToken);
  for (let i = 0; i < 125; i++) await call(request, 'POST', `/messages/${dm.id}`, { content: `Newer ordinary message ${i}`, threadId: task.id }, s.a.accessToken);
  for (let i = 0; i < 24; i++) await call(request, 'POST', `/messages/${s.channel.id}`, { content: `${needle} related result ${i}` }, s.a.accessToken);
  await login(page, s.alice);
  const dialog = await search(page, `?${needle}`);
  await expect(dialog.getByRole('button', { name: 'Messages', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await expect(dialog.getByRole('option').filter({ hasText: needle }).first()).toBeVisible();
  await dialog.getByRole('option', { name: 'View all results', exact: true }).click();
  await expect(page).toHaveURL(/search/);
  await expect(page.getByText(`${needle} old task decision`, { exact: true })).toHaveCount(0);
  await page.getByRole('button', { name: /Load more/ }).click();
  await page.getByText(`${needle} old task decision`, { exact: true }).click();
  await expect(page).toHaveURL(new RegExp(`/dm/${dm.id}`));
  await expect(page).toHaveURL(new RegExp(`threadId=${task.id}`));
  const target = page.getByLabel('Selected search message');
  await expect(target).toContainText('old task decision');
  await expect(target).toHaveAttribute('data-highlighted-message', selected.id);
  await assertContained(page, '[data-highlighted-message]');
  await page.screenshot({ path: `${test.info().outputDir}/old-message-context.png` });
  await page.reload();
  await expect(page.getByLabel('Selected search message')).toContainText('old task decision');
  await page.getByRole('button', { name: 'Back to latest', exact: true }).click();
  await expect(page.locator('[contenteditable=true]').first()).toBeFocused();
  await expect(page.getByText('Newer ordinary message 124', { exact: true })).toBeVisible();
});
test('cookie-authenticated search hides another members DM', async ({ page, request }) => {
  const s = await seedWorkspace(request);
  const outsider = identity('Outsider Search');
  const outside = await call(request, 'POST', '/auth/register', outsider);
  const invite = await call(request, 'POST', '/invites/create', { workspaceId: s.workspace.id, email: outsider.email }, s.a.accessToken);
  await call(request, 'POST', '/invites/accept', { inviteId: invite.id }, outside.accessToken);
  const hidden = await call(request, 'POST', '/conversations/dm', { workspaceId: s.workspace.id, otherUserId: outside.user.id }, s.b.accessToken);
  const needle = `privateneedle${randomUUID().replaceAll('-', '')}`;
  const message = await call(request, 'POST', `/messages/${hidden.id}`, { content: needle }, s.b.accessToken);
  await login(page, s.alice);
  const response = await page.request.get(`${apiURL}/search/messages?q=${needle}`, { headers: webHeaders });
  expect(response.status()).toBe(200);
  expect((await response.json()).items).toEqual([]);
  const context = await page.request.get(`${apiURL}/search/messages/${message.id}/context`, { headers: webHeaders });
  expect(context.status()).toBe(404);
  const publicRead = await request.get(`${apiURL}/search/jump?q=general`);
  expect(publicRead.status()).toBe(401);
});
